main_api_cols = [
    "commodity",
    "commodity_subgroup_name",
    "market_and_exchange_names",
    "cftc_contract_market_code",
    "report_date_as_yyyy_mm_dd",
    "yyyy_report_week_ww",
    "open_interest_all",
]

report_api_cols = {
    "legacy": [
        "noncomm_positions_long_all",
        "noncomm_positions_short_all",
        "comm_positions_long_all",
        "comm_positions_short_all",
        "tot_rept_positions_long_all",
        "tot_rept_positions_short",
        "nonrept_positions_long_all",
        "nonrept_positions_short_all",
        "pct_of_oi_noncomm_long_all",
        "pct_of_oi_noncomm_short_all",
        "pct_of_oi_comm_long_all",
        "pct_of_oi_comm_short_all",
        "pct_of_oi_tot_rept_long_all",
        "pct_of_oi_tot_rept_short",
        "pct_of_oi_nonrept_long_all",
        "pct_of_oi_nonrept_short_all",
    ],
    "disaggregated": [
        "prod_merc_positions_long",
        "prod_merc_positions_short",
        "swap_positions_long_all",
        "swap__positions_short_all",
        "m_money_positions_long_all",
        "m_money_positions_short_all",
        "other_rept_positions_long",
        "other_rept_positions_short",
        "tot_rept_positions_long_all",
        "tot_rept_positions_short",
        "nonrept_positions_long_all",
        "nonrept_positions_short_all",
        "pct_of_oi_prod_merc_long",
        "pct_of_oi_prod_merc_short",
        "pct_of_oi_swap_long_all",
        "pct_of_oi_swap_short_all",
        "pct_of_oi_m_money_long_all",
        "pct_of_oi_m_money_short_all",
        "pct_of_oi_other_rept_long",
        "pct_of_oi_other_rept_short",
        "pct_of_oi_tot_rept_long_all",
        "pct_of_oi_tot_rept_short",
        "pct_of_oi_nonrept_long_all",
        "pct_of_oi_nonrept_short_all",
    ],
    "tff": [
        "dealer_positions_long_all",
        "dealer_positions_short_all",
        "asset_mgr_positions_long",
        "asset_mgr_positions_short",
        "lev_money_positions_long",
        "lev_money_positions_short",
        "other_rept_positions_long",
        "other_rept_positions_short",
        "tot_rept_positions_long_all",
        "tot_rept_positions_short",
        "nonrept_positions_long_all",
        "nonrept_positions_short_all",
        "pct_of_oi_dealer_long_all",
        "pct_of_oi_dealer_short_all",
        "pct_of_oi_asset_mgr_long",
        "pct_of_oi_asset_mgr_short",
        "pct_of_oi_lev_money_long",
        "pct_of_oi_lev_money_short",
        "pct_of_oi_other_rept_long",
        "pct_of_oi_other_rept_short",
        "pct_of_oi_tot_rept_long_all",
        "pct_of_oi_tot_rept_short",
        "pct_of_oi_nonrept_long_all",
        "pct_of_oi_nonrept_short_all",
    ],
}

root_cols = {
    "legacy": {
        "comm_positions",
        "noncomm_positions",
        "nonrept_positions",
        "tot_rept_positions",
        "pct_of_oi_tot_rept",
        "pct_of_oi_nonrept",
        "pct_of_oi_comm",
        "pct_of_oi_noncomm",
    },
    "disaggregated": {
        "prod_merc_positions",
        "swap_positions",
        "nonrept_positions",
        "other_rept_positions",
        "m_money_positions",
        "tot_rept_positions",
        "pct_of_oi_prod_merc",
        "pct_of_oi_m_money",
        "pct_of_oi_other_rept",
        "pct_of_oi_tot_rept",
        "pct_of_oi_swap",
        "pct_of_oi_nonrept",
    },
    "tff": {
        "tot_rept_positions",
        "lev_money_positions",
        "asset_mgr_positions",
        "nonrept_positions",
        "other_rept_positions",
        "dealer_positions",
        "pct_of_oi_tot_rept",
        "pct_of_oi_nonrept",
        "pct_of_oi_lev_money",
        "pct_of_oi_other_rept",
        "pct_of_oi_dealer",
        "pct_of_oi_asset_mgr",
    },
}
root_cols_desc = {
    "legacy": {
        "comm": "Commercial",
        "noncomm": "Non-Commercial",
        "nonrept": "Non-Reportable",
        "tot_rept": "Total Reportable",
    },
    "disaggregated": {
        "prod_merc": "Producer/Merchant",
        "swap": "Swap Dealer",
        "other_rept": "Other Reportable",
        "m_money": "Managed Money",
        "tot_rept": "Total Reportable",
        "nonrept": "Non-Reportable",
    },
    "tff": {
        "tot_rept": "Total Reportable",
        "lev_money": "Lev. Money",
        "asset_mgr": "Asset Manager",
        "nonrept": "Non-Reportable",
        "dealer": "Dealer",
        "other_rept": "Other Reportable",
    },
}
