reports_tables_names = {
    "report_legacy_futures_only": "report_legacy",
    "report_legacy_combined": "report_legacy",
    "report_disaggregated_futures_only": "report_disaggregated",
    "report_disaggregated_combined": "report_disaggregated",
    "report_tff_futures_only": "report_tff",
    "report_tff_combined": "report_tff",
    "report_suplemental_cit": "report_suplemental_cit",
}

positions_percentages_root_of_cols = {
    "report_legacy": {
        "Commercial": {
            "positions": "comm_positions",
            "percentages": "pct_of_oi_comm",
        },
        "Non-Commercial": {
            "positions": "noncomm_positions",
            "percentages": "pct_of_oi_noncomm",
        },
        "Non-Reportable": {
            "positions": "nonrept_positions",
            "percentages": "pct_of_oi_nonrept",
        },
        "Total Reportable": {
            "positions": "tot_rept_positions",
            "percentages": "pct_of_oi_tot_rept",
        },
    },
    "report_supplemental_cit": {
        "Non-Commercial - No CIT": {
            "positions": "NComm_Postions_NoCIT",
            "percentages": "pct_oi_noncomm_nocit",
        },
        "Commercial - No CIT": {
            "positions": "comm_positions_NoCIT",
            "percentages": "pct_oi_comm_nocit",
        },
        "CIT": {
            "positions": "cit_positions",
            "percentages": "pct_oi_cit",
        },
        "Non-Reportable": {
            "positions": "nonrept_positions",
            "percentages": "pct_oi_nonrept_nocit",
        },
        "Total Reportable": {
            "positions": "tot_rept_positions",
            "percentages": "pct_oi_tot_rept_nocit",
        },
    },
    "report_disaggregated": {
        "Producer/Merchant": {
            "positions": "prod_merc_positions",
            "percentages": "pct_of_oi_prod_merc",
        },
        "Swap Dealers": {
            "positions": "swap_positions",
            "percentages": "pct_of_oi_swap",
        },
        "Managed Money": {
            "positions": "m_money_positions",
            "percentages": "pct_of_oi_m_money",
        },
        "Other Reportable": {
            "positions": "other_rept_positions",
            "percentages": "pct_of_oi_other_rept",
        },
        "Total Reportable": {
            "positions": "tot_rept_positions",
            "percentages": "pct_of_oi_tot_rept",
        },
        "Non-Reportable": {
            "positions": "nonrept_positions",
            "percentages": "pct_of_oi_nonrept",
        },
    },
    "report_tff": {
        "Dealer": {
            "positions": "dealer_positions",
            "percentages": "pct_of_oi_dealer",
        },
        "Asset Manager": {
            "positions": "asset_mgr_positions",
            "percentages": "pct_of_oi_asset_mgr",
        },
        "Leveraged Money": {
            "positions": "lev_money_positions",
            "percentages": "pct_of_oi_lev_money",
        },
        "Other Reportable": {
            "positions": "other_rept_positions",
            "percentages": "pct_of_oi_other_rept",
        },
        "Total Reportable": {
            "positions": "tot_rept_positions",
            "percentages": "pct_of_oi_tot_rept",
        },
        "Non-Reportable": {
            "positions": "nonrept_positions",
            "percentages": "pct_of_oi_nonrept",
        },
    },
}

root_of_cols = {
    "report_legacy": {
        "positions": {
            "comm_positions": "Commercial",
            "noncomm_positions": "Non-Commercial",
            "nonrept_positions": "Non-Reportable",
            "tot_rept_positions": "Total Reportable",
        },
        "concentration": {
            "conc_gross_le_4_tdr": "Concentration Gross Le 4 Tdr",
            "conc_gross_le_8_tdr": "Concentration Gross Le 8 Tdr",
            "conc_net_le_4_tdr": "Concentration Net Le 4 Tdr",
            "conc_net_le_8_tdr": "Concentration Net Le 8 Tdr",
        },
        "percentages": {
            "pct_of_oi_noncomm": "Percentage Non-Commercial",
            "pct_of_oi_comm": "Percentage Commercial",
            "pct_of_oi_tot_rept": "Percentage Total Report",
            "pct_of_oi_nonrept": "Percentage Non-Reportable",
        },
        "traders": {
            "traders_noncomm": "Traders Non-Commercial",
            "traders_comm": "Traders Commercial",
            "traders_tot_rept": "Traders Total Report",
        },
    },
    "report_supplemental_cit": {
        "positions": {
            "NComm_Postions_NoCIT": "Non-Commercial - No CIT",
            "comm_positions_NoCIT": "Commercial - No CIT",
            "tot_rept_positions": "Total Reportable",
            "nonrept_positions": "Non-Reportable",
            "cit_positions": "CIT",
        },
        "concentration": {},  # Add concentration data here
        "percentages": {
            "pct_oi_noncomm_nocit": "Percentage in Non-Commercial Positions No CIT",
            "pct_oi_comm_nocit": "Percentage in Commercial Positions No CIT",
            "pct_oi_tot_rept_nocit": "Percentage in Total Reportable Positions No CIT",
            "pct_oi_nonrept_nocit": "Percentage in Non-Reportable Positions No CIT",
            "pct_oi_cit": "Percentage in CIT Positions",
        },
        "traders": {
            "Traders_NonComm_NoCIT": "Number of Traders with Non-Commercial Positions No CIT",
            "traders_comm_nocit": "Number of Traders with Commercial Positions No CIT",
            "Traders_Tot_Rept_NoCIT": "Number of Traders with Total Reportable Positions No CIT",
            "traders_cit": "Number of Traders with CIT Positions",
        },
    },
    "report_disaggregated": {
        "positions": {
            "prod_merc_positions": "Producer/Merchant",
            "swap_positions": "Swap Dealers",
            "m_money_positions": "Managed Money",
            "other_rept_positions": "Other Reportable",
            "tot_rept_positions": "Total Reportable",
            "nonrept_positions": "Non-Reportable",
        },
        "concentration": {
            "conc_gross_le_4_tdr": "Concentration Gross Le 4 Tdr",
            "conc_gross_le_8_tdr": "Concentration Gross Le 8 Tdr",
            "conc_net_le_4_tdr": "Concentration Net Le 4 Tdr",
            "conc_net_le_8_tdr": "Concentration Net Le 8 Tdr",
        },
        "percentages": {
            "pct_of_oi_prod_merc": "Percentage Producer/Merchant",
            "pct_of_oi_swap": "Percentage Swap Dealers",
            "pct_of_oi_m_money": "Percentage Managed Money",
            "pct_of_oi_other_rept": "Percentage Other Reportable",
            "pct_of_oi_tot_rept": "Percentage Total Report",
            "pct_of_oi_nonrept": "Percentage Non-Reportable",
        },
        "traders": {
            "traders_prod_merc": "Traders Producer/Merchant",
            "traders_swap": "Traders Swap Dealers",
            "traders_m_money": "Traders Managed Money",
            "traders_other_rept": "Traders Other Reportable",
            "traders_tot_rept": "Traders Total Report",
        },
    },
    "report_tff": {
        "positions": {
            "dealer_positions": "Dealer",
            "asset_mgr_positions": "Asset Manager",
            "lev_money_positions": "Leveraged Money",
            "other_rept_positions": "Other Reportable",
            "tot_rept_positions": "Total Reportable",
            "nonrept_positions": "Non-Reportable",
        },
        "concentration": {
            "conc_gross_le_4_tdr": "Concentration Gross Le 4 Tdr",
            "conc_gross_le_8_tdr": "Concentration Gross Le 8 Tdr",
            "conc_net_le_4_tdr": "Concentration Net Le 4 Tdr",
            "conc_net_le_8_tdr": "Concentration Net Le 8 Tdr",
        },
        "percentages": {
            "pct_of_oi_dealer": "Percentage Dealer",
            "pct_of_oi_asset_mgr": "Percentage Asset Manager",
            "pct_of_oi_lev_money": "Percentage Leveraged Money",
            "pct_of_oi_other_rept": "Percentage Other Reportable",
            "pct_of_oi_tot_rept": "Percentage Total Report",
            "pct_of_oi_nonrept": "Percentage Non-Reportable",
        },
        "traders": {
            "traders_dealer": "Traders Dealer",
            "traders_asset_mgr": "Traders Asset Manager",
            "traders_lev_money": "Traders Leveraged Money",
            "traders_other_rept": "Traders Other Reportable",
            "traders_tot_rept": "Traders Total Report",
        },
    },
}

full_cols = {
    "report_legacy": {
        "positions": {
            "noncomm_positions_long_all": "Non-Commercial Positions Long All",
            "noncomm_positions_short_all": "Non-Commercial Positions Short All",
            "comm_positions_long_all": "Commercial Positions Long All",
            "comm_positions_short_all": "Commercial Positions Short All",
            "tot_rept_positions_long_all": "Total Report Positions Long All",
            "tot_rept_positions_short": "Total Report Positions Short",
            "nonrept_positions_long_all": "Non-Rept Positions Long All",
            "nonrept_positions_short_all": "Non-Rept Positions Short All",
        },
        "percentages": {
            "pct_of_oi_noncomm_long_all": "Percentage Non-Commercial Long All",
            "pct_of_oi_noncomm_short_all": "Percentage Non-Commercial Short All",
            "pct_of_oi_comm_long_all": "Percentage Commercial Long All",
            "pct_of_oi_comm_short_all": "Percentage Commercial Short All",
            "pct_of_oi_tot_rept_long_all": "Percentage Total Report Long All",
            "pct_of_oi_tot_rept_short": "Percentage Total Report Short",
            "pct_of_oi_nonrept_long_all": "Percentage Non-Rept Long All",
            "pct_of_oi_nonrept_short_all": "Percentage Non-Rept Short All",
        },
        "traders": {
            "traders_noncomm_long_all": "Traders Non-Commercial Long All",
            "traders_noncomm_short_all": "Traders Non-Commercial Short All",
            "traders_comm_long_all": "Traders Commercial Long All",
            "traders_comm_short_all": "Traders Commercial Short All",
            "traders_tot_rept_short_all": "Traders Total Report Short All",
            "traders_tot_rept_long_all": "Traders Total Report Long All",
        },
        "concentration": {
            "conc_gross_le_4_tdr_long": "Concentration Gross Le 4 Tdr Long",
            "conc_gross_le_4_tdr_short": "Concentration Gross Le 4 Tdr Short",
            "conc_gross_le_8_tdr_long": "Concentration Gross Le 8 Tdr Long",
            "conc_gross_le_8_tdr_short": "Concentration Gross Le 8 Tdr Short",
            "conc_net_le_4_tdr_long_all": "Concentration Net Le 4 Tdr Long All",
            "conc_net_le_4_tdr_short_all": "Concentration Net Le 4 Tdr Short All",
            "conc_net_le_8_tdr_long_all": "Concentration Net Le 8 Tdr Long All",
            "conc_net_le_8_tdr_short_all": "Concentration Net Le 8 Tdr Short All",
        },
    },
    "report_supplemental_cit": {
        "positions": {
            "NComm_Postions_Long_All_NoCIT": "Non-Commercial Positions Long All No CIT",
            "NComm_Postions_Short_All_NoCIT": "Non-Commercial Positions Short All No CIT",
            "comm_positions_long_all_nocit": "Commercial Positions Long All No CIT",
            "Comm_Positions_Short_All_NoCIT": "Commercial Positions Short All No CIT",
            "tot_rept_positions_long_all": "Total Reportable Positions Long All",
            "tot_rept_positions_short": "Total Reportable Positions Short",
            "nonrept_positions_long_all": "Non-Reportable Positions Long All",
            "nonrept_positions_short_all": "Non-Reportable Positions Short All",
            "cit_positions_long_all": "CIT Positions Long All",
            "cit_positions_short_all": "CIT Positions Short All",
        },
        "percentages": {
            "pct_oi_noncomm_long_all_nocit": "Percentage in Non-Commercial Long Positions All No CIT",
            "Pct_OI_NonComm_Short_All_NoCIT": "Percentage in Non-Commercial Short Positions All No CIT",
            "pct_oi_comm_long_all_nocit": "Percentage in Commercial Long Positions All No CIT",
            "pct_oi_comm_short_all_nocit": "Percentage in Commercial Short Positions All No CIT",
            "Pct_OI_Tot_Rept_Long_All_NoCIT": "Percentage in Total Reportable Long Positions All No CIT",
            "Pct_OI_Tot_Rept_Short_All_NoCIT": "Percentage in Total Reportable Short Positions All No CIT",
            "pct_oi_nonrept_long_all_nocit": "Percentage in Non-Reportable Long Positions All No CIT",
            "Pct_OI_NonRept_Short_All_NoCIT": "Percentage in Non-Reportable Short Positions All No CIT",
            "pct_oi_cit_long_all": "Percentage in CIT Long Positions All",
            "pct_oi_cit_short_all": "Percentage in CIT Short Positions All",
        },
        "traders": {
            "Traders_NonComm_Long_All_NoCIT": "Number of Traders with Non-Commercial Long Positions All No CIT",
            "Traders_NonComm_Short_All_NoCIT": "Number of Traders with Non-Commercial Short Positions All No CIT",
            "traders_comm_long_all_nocit": "Number of Traders with Commercial Long Positions All No CIT",
            "traders_comm_short_all_nocit": "Number of Traders with Commercial Short Positions All No CIT",
            "Traders_Tot_Rept_Long_All_NoCIT": "Number of Traders with Total Reportable Long Positions All No CIT",
            "Traders_Tot_Rept_Short_All_NoCIT": "Number of Traders with Total Reportable Short Positions All No CIT",
            "traders_cit_long_all": "Number of Traders with CIT Long Positions All",
            "traders_cit_short_all": "Number of Traders with CIT Short Positions All",
        },
    },
    "report_disaggregated": {
        "positions": {
            "prod_merc_positions_long": "Producer/Merchant Positions Long",
            "prod_merc_positions_short": "Producer/Merchant Positions Short",
            "swap_positions_long_all": "Swap Positions Long All",
            "swap__positions_short_all": "Swap Positions Short All",
            "m_money_positions_long_all": "Managed Money Positions Long All",
            "m_money_positions_short_all": "Managed Money Positions Short All",
            "other_rept_positions_long": "Other Reportable Positions Long",
            "other_rept_positions_short": "Other Reportable Positions Short",
            "tot_rept_positions_long_all": "Total Report Positions Long All",
            "tot_rept_positions_short": "Total Report Positions Short",
            "nonrept_positions_long_all": "Non-Reportable Positions Long All",
            "nonrept_positions_short_all": "Non-Reportable Positions Short All",
        },
        "percentages": {
            "pct_of_oi_prod_merc_long": "Percentage Producer/Merchant Long",
            "pct_of_oi_prod_merc_short": "Percentage Producer/Merchant Short",
            "pct_of_oi_swap_long_all": "Percentage Swap Long All",
            "pct_of_oi_swap_short_all": "Percentage Swap Short All",
            "pct_of_oi_m_money_long_all": "Percentage Managed Money Long All",
            "pct_of_oi_m_money_short_all": "Percentage Managed Money Short All",
            "pct_of_oi_other_rept_long": "Percentage Other Reportable Long",
            "pct_of_oi_other_rept_short": "Percentage Other Reportable Short",
            "pct_of_oi_tot_rept_long_all": "Percentage Total Report Long All",
            "pct_of_oi_tot_rept_short": "Percentage Total Report Short",
            "pct_of_oi_nonrept_long_all": "Percentage Non-Reportable Long All",
            "pct_of_oi_nonrept_short_all": "Percentage Non-Reportable Short All",
        },
        "traders": {
            "traders_prod_merc_long_all": "Traders Producer/Merchant Long All",
            "traders_prod_merc_short_all": "Traders Producer/Merchant Short All",
            "traders_swap_long_all": "Traders Swap Long All",
            "traders_swap_short_all": "Traders Swap Short All",
            "traders_m_money_long_all": "Traders Managed Money Long All",
            "traders_m_money_short_all": "Traders Managed Money Short All",
            "traders_other_rept_long_all": "Traders Other Reportable Long All",
            "traders_other_rept_short": "Traders Other Reportable Short",
            "traders_tot_rept_long_all": "Traders Total Report Long All",
            "traders_tot_rept_short_all": "Traders Total Report Short All",
        },
        "concentration": {
            "conc_gross_le_4_tdr_long": "Concentration Gross Le 4 Tdr Long",
            "conc_gross_le_4_tdr_short": "Concentration Gross Le 4 Tdr Short",
            "conc_gross_le_8_tdr_long": "Concentration Gross Le 8 Tdr Long",
            "conc_gross_le_8_tdr_short": "Concentration Gross Le 8 Tdr Short",
            "conc_net_le_4_tdr_long_all": "Concentration Net Le 4 Tdr Long All",
            "conc_net_le_4_tdr_short_all": "Concentration Net Le 4 Tdr Short All",
            "conc_net_le_8_tdr_long_all": "Concentration Net Le 8 Tdr Long All",
            "conc_net_le_8_tdr_short_all": "Concentration Net Le 8 Tdr Short All",
        },
    },
    "report_tff": {
        "positions": {
            "dealer_positions_long_all": "Dealer Positions Long All",
            "dealer_positions_short_all": "Dealer Positions Short All",
            "asset_mgr_positions_long": "Asset Manager Positions Long",
            "asset_mgr_positions_short": "Asset Manager Positions Short",
            "lev_money_positions_long": "Lev Money Positions Long",
            "lev_money_positions_short": "Lev Money Positions Short",
            "other_rept_positions_long": "Other Reportable Positions Long",
            "other_rept_positions_short": "Other Reportable Positions Short",
            "tot_rept_positions_long_all": "Total Report Positions Long All",
            "tot_rept_positions_short": "Total Report Positions Short",
            "nonrept_positions_long_all": "Non-Reportable Positions Long All",
            "nonrept_positions_short_all": "Non-Reportable Positions Short All",
        },
        "percentages": {
            "pct_of_oi_dealer_long_all": "Percentage Dealer Long All",
            "pct_of_oi_dealer_short_all": "Percentage Dealer Short All",
            "pct_of_oi_asset_mgr_long": "Percentage Asset Manager Long",
            "pct_of_oi_asset_mgr_short": "Percentage Asset Manager Short",
            "pct_of_oi_lev_money_long": "Percentage Lev Money Long",
            "pct_of_oi_lev_money_short": "Percentage Lev Money Short",
            "pct_of_oi_other_rept_long": "Percentage Other Reportable Long",
            "pct_of_oi_other_rept_short": "Percentage Other Reportable Short",
            "pct_of_oi_tot_rept_long_all": "Percentage Total Report Long All",
            "pct_of_oi_tot_rept_short": "Percentage Total Report Short",
            "pct_of_oi_nonrept_long_all": "Percentage Non-Reportable Long All",
            "pct_of_oi_nonrept_short_all": "Percentage Non-Reportable Short All",
        },
        "traders": {
            "traders_dealer_long_all": "Traders Dealer Long All",
            "traders_dealer_short_all": "Traders Dealer Short All",
            "traders_asset_mgr_long_all": "Traders Asset Manager Long All",
            "traders_asset_mgr_short_all": "Traders Asset Manager Short All",
            "traders_lev_money_long_all": "Traders Lev Money Long All",
            "traders_lev_money_short_all": "Traders Lev Money Short All",
            "traders_other_rept_long_all": "Traders Other Reportable Long All",
            "traders_other_rept_short": "Traders Other Reportable Short",
            "traders_tot_rept_long_all": "Traders Total Report Long All",
            "traders_tot_rept_short_all": "Traders Total Report Short All",
        },
        "concentration": {
            "conc_gross_le_4_tdr_long": "Concentration Gross Le 4 Tdr Long",
            "conc_gross_le_4_tdr_short": "Concentration Gross Le 4 Tdr Short",
            "conc_gross_le_8_tdr_long": "Concentration Gross Le 8 Tdr Long",
            "conc_gross_le_8_tdr_short": "Concentration Gross Le 8 Tdr Short",
            "conc_net_le_4_tdr_long_all": "Concentration Net Le 4 Tdr Long All",
            "conc_net_le_4_tdr_short_all": "Concentration Net Le 4 Tdr Short All",
            "conc_net_le_8_tdr_long_all": "Concentration Net Le 8 Tdr Long All",
            "conc_net_le_8_tdr_short_all": "Concentration Net Le 8 Tdr Short All",
        },
    },
}

full_cols_with_net = {
    "report_legacy": {
        "positions": {
            "noncomm_positions_long_all": "Non-Commercial Positions Long All",
            "noncomm_positions_short_all": "Non-Commercial Positions Short All",
            "comm_positions_long_all": "Commercial Positions Long All",
            "comm_positions_short_all": "Commercial Positions Short All",
            "tot_rept_positions_long_all": "Total Report Positions Long All",
            "tot_rept_positions_short_all": "Total Report Positions Short",
            "nonrept_positions_long_all": "Non-Rept Positions Long All",
            "nonrept_positions_short_all": "Non-Rept Positions Short All",
            "noncomm_positions_net_all": "Non-Commercial Positions Net All",
            "comm_positions_net_all": "Commercial Positions Net All",
            "tot_rept_positions_net_all": "Total Report Positions Net All",
            "nonrept_positions_net_all": "Non-Rept Positions Net All",
        },
        "percentages": {
            "pct_of_oi_noncomm_long_all": "Percentage Non-Commercial Long All",
            "pct_of_oi_noncomm_short_all": "Percentage Non-Commercial Short All",
            "pct_of_oi_comm_long_all": "Percentage Commercial Long All",
            "pct_of_oi_comm_short_all": "Percentage Commercial Short All",
            "pct_of_oi_tot_rept_long_all": "Percentage Total Report Long All",
            "pct_of_oi_tot_rept_short_all": "Percentage Total Report Short",
            "pct_of_oi_nonrept_long_all": "Percentage Non-Rept Long All",
            "pct_of_oi_nonrept_short_all": "Percentage Non-Rept Short All",
            "pct_of_oi_noncomm_net_all": "Percentage Non-Commercial Long All Net All",
            "pct_of_oi_comm_net_all": "Percentage Commercial Long All Net All",
            "pct_of_oi_tot_rept_net_all": "Percentage Total Report Long All Net All",
            "pct_of_oi_nonrept_net_all": "Percentage Non-Rept Long All Net All",
        },
        "traders": {
            "traders_noncomm_long_all": "Traders Non-Commercial Long All",
            "traders_noncomm_short_all": "Traders Non-Commercial Short All",
            "traders_comm_long_all": "Traders Commercial Long All",
            "traders_comm_short_all": "Traders Commercial Short All",
            "traders_tot_rept_short_all": "Traders Total Report Short All",
            "traders_tot_rept_long_all": "Traders Total Report Long All",
            "traders_noncomm_net_all": "Traders Non-Commercial Net All",
            "traders_comm_net_all": "Traders Commercial Net All",
            "traders_tot_rept_net_all": "Traders Total Report Net All",
        },
        "concentration": {
            "conc_gross_le_4_tdr_long": "Concentration Gross Le 4 Tdr Long",
            "conc_gross_le_4_tdr_short_all": "Concentration Gross Le 4 Tdr Short",
            "conc_gross_le_8_tdr_long": "Concentration Gross Le 8 Tdr Long",
            "conc_gross_le_8_tdr_short_all": "Concentration Gross Le 8 Tdr Short",
            "conc_net_le_4_tdr_long_all": "Concentration Net Le 4 Tdr Long All",
            "conc_net_le_4_tdr_short_all": "Concentration Net Le 4 Tdr Short All",
            "conc_net_le_8_tdr_long_all": "Concentration Net Le 8 Tdr Long All",
            "conc_net_le_8_tdr_short_all": "Concentration Net Le 8 Tdr Short All",
            "conc_net_le_4_tdr_net_all": "Concentration Net Le 4 Tdr Net All",
            "conc_net_le_8_tdr_net_all": "Concentration Net Le 8 Tdr Net All",
            "conc_gross_le_4_tdr_net": "Concentration Gross Le 4 Tdr Long Net",
            "conc_gross_le_8_tdr_net": "Concentration Gross Le 8 Tdr Long Net",
        },
    },
    "report_supplemental_cit": {
        "positions": {
            "NComm_Postions_Long_All_NoCIT": "Non-Commercial Positions Long All No CIT",
            "NComm_Postions_Short_All_NoCIT": "Non-Commercial Positions Short All No CIT",
            "comm_positions_long_all_nocit": "Commercial Positions Long All No CIT",
            "Comm_Positions_Short_All_NoCIT": "Commercial Positions Short All No CIT",
            "tot_rept_positions_long_all": "Total Reportable Positions Long All",
            "tot_rept_positions_short_all": "Total Reportable Positions Short",
            "nonrept_positions_long_all": "Non-Reportable Positions Long All",
            "nonrept_positions_short_all": "Non-Reportable Positions Short All",
            "cit_positions_long_all": "CIT Positions Long All",
            "cit_positions_short_all": "CIT Positions Short All",
            "tot_rept_positions_net_all": "Total Reportable Positions Net All",
            "nonrept_positions_net_all": "Non-Reportable Positions Net All",
            "cit_positions_net_all": "CIT Positions Net All",
        },
        "percentages": {
            "pct_oi_noncomm_long_all_nocit": "Percentage in Non-Commercial Long Positions All No CIT",
            "Pct_OI_NonComm_Short_All_NoCIT": "Percentage in Non-Commercial Short Positions All No CIT",
            "pct_oi_comm_long_all_nocit": "Percentage in Commercial Long Positions All No CIT",
            "pct_oi_comm_short_all_nocit": "Percentage in Commercial Short Positions All No CIT",
            "Pct_OI_Tot_Rept_Long_All_NoCIT": "Percentage in Total Reportable Long Positions All No CIT",
            "Pct_OI_Tot_Rept_Short_All_NoCIT": "Percentage in Total Reportable Short Positions All No CIT",
            "pct_oi_nonrept_long_all_nocit": "Percentage in Non-Reportable Long Positions All No CIT",
            "Pct_OI_NonRept_Short_All_NoCIT": "Percentage in Non-Reportable Short Positions All No CIT",
            "pct_oi_cit_long_all": "Percentage in CIT Long Positions All",
            "pct_oi_cit_short_all": "Percentage in CIT Short Positions All",
            "pct_oi_cit_net_all": "Percentage in CIT Long Positions All Net All",
        },
        "traders": {
            "Traders_NonComm_Long_All_NoCIT": "Number of Traders with Non-Commercial Long Positions All No CIT",
            "Traders_NonComm_Short_All_NoCIT": "Number of Traders with Non-Commercial Short Positions All No CIT",
            "traders_comm_long_all_nocit": "Number of Traders with Commercial Long Positions All No CIT",
            "traders_comm_short_all_nocit": "Number of Traders with Commercial Short Positions All No CIT",
            "Traders_Tot_Rept_Long_All_NoCIT": "Number of Traders with Total Reportable Long Positions All No CIT",
            "Traders_Tot_Rept_Short_All_NoCIT": "Number of Traders with Total Reportable Short Positions All No CIT",
            "traders_cit_long_all": "Number of Traders with CIT Long Positions All",
            "traders_cit_short_all": "Number of Traders with CIT Short Positions All",
            "traders_cit_net_all": "Number of Traders with CIT Long Positions All Net All",
        },
    },
    "report_disaggregated": {
        "positions": {
            "prod_merc_positions_long": "Producer/Merchant Positions Long",
            "prod_merc_positions_short_all": "Producer/Merchant Positions Short",
            "swap_positions_long_all": "Swap Positions Long All",
            "swap__positions_short_all": "Swap Positions Short All",
            "m_money_positions_long_all": "Managed Money Positions Long All",
            "m_money_positions_short_all": "Managed Money Positions Short All",
            "other_rept_positions_long": "Other Reportable Positions Net",
            "other_rept_positions_short_all": "Other Reportable Positions Short",
            "tot_rept_positions_long_all": "Total Report Positions Long All",
            "tot_rept_positions_short_all": "Total Report Positions Short",
            "nonrept_positions_long_all": "Non-Reportable Positions Long All",
            "nonrept_positions_short_all": "Non-Reportable Positions Short All",
            "prod_merc_positions_net_all": "Producer/Merchant Positions Net",
            "swap_positions_net_all": "Swap Positions Net All",
            "m_money_positions_net_all": "Managed Money Positions Net All",
            "tot_rept_positions_net_all": "Total Report Positions Net All",
            "nonrept_positions_net_all": "Non-Reportable Positions Net All",
            "prod_merc_positions_net": "Producer/Merchant Positions Long Net",
            "other_rept_positions_net": "Other Reportable Positions Net Net",
        },
        "percentages": {
            "pct_of_oi_prod_merc_long": "Percentage Producer/Merchant Long",
            "pct_of_oi_prod_merc_short_all": "Percentage Producer/Merchant Short",
            "pct_of_oi_swap_long_all": "Percentage Swap Long All",
            "pct_of_oi_swap_short_all": "Percentage Swap Short All",
            "pct_of_oi_m_money_long_all": "Percentage Managed Money Long All",
            "pct_of_oi_m_money_short_all": "Percentage Managed Money Short All",
            "pct_of_oi_other_rept_long": "Percentage Other Reportable Long",
            "pct_of_oi_other_rept_short_all": "Percentage Other Reportable Short",
            "pct_of_oi_tot_rept_long_all": "Percentage Total Report Long All",
            "pct_of_oi_tot_rept_short_all": "Percentage Total Report Short",
            "pct_of_oi_nonrept_long_all": "Percentage Non-Reportable Long All",
            "pct_of_oi_nonrept_short_all": "Percentage Non-Reportable Short All",
            "pct_of_oi_swap_net_all": "Percentage Swap Long All Net All",
            "pct_of_oi_m_money_net_all": "Percentage Managed Money Long All Net All",
            "pct_of_oi_tot_rept_net_all": "Percentage Total Report Long All Net All",
            "pct_of_oi_nonrept_net_all": "Percentage Non-Reportable Long All Net All",
            "pct_of_oi_prod_merc_net": "Percentage Producer/Merchant Long Net",
            "pct_of_oi_other_rept_net": "Percentage Other Reportable Long Net",
        },
        "traders": {
            "traders_prod_merc_long_all": "Traders Producer/Merchant Long All",
            "traders_prod_merc_short_all": "Traders Producer/Merchant Short All",
            "traders_swap_long_all": "Traders Swap Long All",
            "traders_swap_short_all": "Traders Swap Short All",
            "traders_m_money_long_all": "Traders Managed Money Long All",
            "traders_m_money_short_all": "Traders Managed Money Short All",
            "traders_other_rept_long_all": "Traders Other Reportable Long All",
            "traders_other_rept_short_all": "Traders Other Reportable Short",
            "traders_tot_rept_long_all": "Traders Total Report Long All",
            "traders_tot_rept_short_all": "Traders Total Report Short All",
            "traders_prod_merc_net_all": "Traders Producer/Merchant Net All",
            "traders_swap_net_all": "Traders Swap Net All",
            "traders_m_money_net_all": "Traders Managed Money Net All",
            "traders_other_rept_net_all": "Traders Other Reportable Net All",
            "traders_tot_rept_net_all": "Traders Total Report Net All",
        },
        "concentration": {
            "conc_gross_le_4_tdr_long": "Concentration Gross Le 4 Tdr Long",
            "conc_gross_le_4_tdr_short_all": "Concentration Gross Le 4 Tdr Short",
            "conc_gross_le_8_tdr_long": "Concentration Gross Le 8 Tdr Long",
            "conc_gross_le_8_tdr_short_all": "Concentration Gross Le 8 Tdr Short",
            "conc_net_le_4_tdr_long_all": "Concentration Net Le 4 Tdr Long All",
            "conc_net_le_4_tdr_short_all": "Concentration Net Le 4 Tdr Short All",
            "conc_net_le_8_tdr_long_all": "Concentration Net Le 8 Tdr Long All",
            "conc_net_le_8_tdr_short_all": "Concentration Net Le 8 Tdr Short All",
            "conc_net_le_4_tdr_net_all": "Concentration Net Le 4 Tdr Net All",
            "conc_net_le_8_tdr_net_all": "Concentration Net Le 8 Tdr Net All",
            "conc_gross_le_4_tdr_net": "Concentration Gross Le 4 Tdr Long Net",
            "conc_gross_le_8_tdr_net": "Concentration Gross Le 8 Tdr Long Net",
        },
    },
    "report_tff": {
        "positions": {
            "dealer_positions_long_all": "Dealer Positions Long All",
            "dealer_positions_short_all": "Dealer Positions Short All",
            "asset_mgr_positions_long": "Asset Manager Positions Long",
            "asset_mgr_positions_short_all": "Asset Manager Positions Short",
            "lev_money_positions_long": "Lev Money Positions Long",
            "lev_money_positions_short_all": "Lev Money Positions Short",
            "other_rept_positions_long": "Other Reportable Positions Long",
            "other_rept_positions_short_all": "Other Reportable Positions Short",
            "tot_rept_positions_long_all": "Total Report Positions Long All",
            "tot_rept_positions_short_all": "Total Report Positions Short",
            "nonrept_positions_long_all": "Non-Reportable Positions Long All",
            "nonrept_positions_short_all": "Non-Reportable Positions Short All",
            "dealer_positions_net_all": "Dealer Positions Net All",
            "tot_rept_positions_net_all": "Total Report Positions Net All",
            "nonrept_positions_net_all": "Non-Reportable Positions Net All",
            "asset_mgr_positions_net_all": "Asset Manager Positions Long Net",
            "lev_money_positions_net_all": "Lev Money Positions Long Net",
            "other_rept_positions_net_all": "Other Reportable Positions Long Net",
        },
        "percentages": {
            "pct_of_oi_dealer_long_all": "Percentage Dealer Long All",
            "pct_of_oi_dealer_short_all": "Percentage Dealer Short All",
            "pct_of_oi_asset_mgr_long": "Percentage Asset Manager Long",
            "pct_of_oi_asset_mgr_short_all": "Percentage Asset Manager Short",
            "pct_of_oi_lev_money_long": "Percentage Lev Money Long",
            "pct_of_oi_lev_money_short_all": "Percentage Lev Money Short",
            "pct_of_oi_other_rept_long": "Percentage Other Reportable Long",
            "pct_of_oi_other_rept_short_all": "Percentage Other Reportable Short",
            "pct_of_oi_tot_rept_long_all": "Percentage Total Report Long All",
            "pct_of_oi_tot_rept_short_all": "Percentage Total Report Short",
            "pct_of_oi_nonrept_long_all": "Percentage Non-Reportable Long All",
            "pct_of_oi_nonrept_short_all": "Percentage Non-Reportable Short All",
            "pct_of_oi_dealer_net_all": "Percentage Dealer Long All Net All",
            "pct_of_oi_tot_rept_net_all": "Percentage Total Report Long All Net All",
            "pct_of_oi_nonrept_net_all": "Percentage Non-Reportable Long All Net All",
            "pct_of_oi_asset_mgr_net": "Percentage Asset Manager Long Net",
            "pct_of_oi_lev_money_net": "Percentage Lev Money Long Net",
            "pct_of_oi_other_rept_net": "Percentage Other Reportable Long Net",
        },
        "traders": {
            "traders_dealer_long_all": "Traders Dealer Long All",
            "traders_dealer_short_all": "Traders Dealer Short All",
            "traders_asset_mgr_long_all": "Traders Asset Manager Long All",
            "traders_asset_mgr_short_all": "Traders Asset Manager Short All",
            "traders_lev_money_long_all": "Traders Lev Money Long All",
            "traders_lev_money_short_all": "Traders Lev Money Short All",
            "traders_other_rept_long_all": "Traders Other Reportable Long All",
            "traders_other_rept_short_all": "Traders Other Reportable Short",
            "traders_tot_rept_long_all": "Traders Total Report Long All",
            "traders_tot_rept_short_all": "Traders Total Report Short All",
            "traders_dealer_net_all": "Traders Dealer Net All",
            "traders_asset_mgr_net_all": "Traders Asset Manager Net All",
            "traders_lev_money_net_all": "Traders Lev Money Net All",
            "traders_other_rept_net_all": "Traders Other Reportable Net All",
            "traders_tot_rept_net_all": "Traders Total Report Net All",
        },
        "concentration": {
            "conc_gross_le_4_tdr_long": "Concentration Gross Le 4 Tdr Long",
            "conc_gross_le_4_tdr_short_all": "Concentration Gross Le 4 Tdr Short",
            "conc_gross_le_8_tdr_long": "Concentration Gross Le 8 Tdr Long",
            "conc_gross_le_8_tdr_short_all": "Concentration Gross Le 8 Tdr Short",
            "conc_net_le_4_tdr_long_all": "Concentration Net Le 4 Tdr Long All",
            "conc_net_le_4_tdr_short_all": "Concentration Net Le 4 Tdr Short All",
            "conc_net_le_8_tdr_long_all": "Concentration Net Le 8 Tdr Long All",
            "conc_net_le_8_tdr_short_all": "Concentration Net Le 8 Tdr Short All",
            "conc_net_le_4_tdr_net_all": "Concentration Net Le 4 Tdr Net All",
            "conc_net_le_8_tdr_net_all": "Concentration Net Le 8 Tdr Net All",
            "conc_gross_le_4_tdr_net": "Concentration Gross Le 4 Tdr Long Net",
            "conc_gross_le_8_tdr_net": "Concentration Gross Le 8 Tdr Long Net",
        },
    },
}
